version: "3"

services:
    igc-network-backend-prod:
        environment:
            - NODE_ENV=production
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dao-backend-prod
        expose:
            - "3000"
        ports:
            - "3000:3000"
        command: npm start