name: Deploy React app on EC2 

env:
  IP_SSH: ${{ secrets.IP_SSH }}
  KEY: ${{ secrets.KEY }}
  

on:
  push:
    branches: [ main ]

jobs:
#   
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy na EC2
        run: |
          echo "${{ secrets.KEY  }}" >> private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i "private_key.pem" "${{ secrets.IP_SSH  }}" '
            sudo docker system prune -a -f 
            ssh-add ~/.ssh/my_project_deploy_key 
            cd /home/ubuntu 
            cd frontend-wealth-managment/
            git pull
            sudo docker-compose -f docker-compose.yml up --build -d
          '

